name: forge2d_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-0

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  flame: ^1.18.0
  flame_forge2d: ^0.18.1
  flame_kenney_xml: ^0.1.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
