name: claat_export
description: A tool to export CLAAT codelabs as markdown.
version: 1.0.0
repository: https://github.com/flutter/codelabs

environment:
  sdk: ^3.0.5

dependencies:
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
