include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/locations.g.dart

linter:
  rules:
    avoid_print: false
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

