include: ../../analysis_options.yaml

analyzer:
  language:
    strict-inference: false
  plugins:
    - custom_lint

linter:
  rules:
    prefer_const_constructors: false
    sort_pub_dependencies: true
