name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: ^3.0.0-417.4.beta

dependencies:
  http: ^0.13.6
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.4

dev_dependencies:
  lints: ^2.0.0
