name: dashclicker
description: A codelab for in-app purchases
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_core: ^1.0.3
  firebase_auth: ^3.3.4
  cloud_functions: ^3.2.4
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.0.1
  in_app_purchase: ^2.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
