name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-java@v3.1.1
        with:
          distribution: 'zulu' # See https://github.com/actions/setup-java#supported-distributions
          java-version: "12.x"
      - uses: subosito/flutter-action@main # TODO: Set pin version once flutter-action releases
        with:
          channel: ${{ matrix.flutter_version }}
      - run: dart --version
      - run: flutter --version
      - run: ./flutter_ci_script_${{ matrix.flutter_version }}.sh
      
